# syntax=docker/dockerfile:1

FROM node:24-alpine

RUN apk upgrade --no-cache

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .
EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
